export enum HomeAssistantDomain {
  automation = "automation",
  button = "button",
  binary_sensor = "binary_sensor",
  climate = "climate",
  cover = "cover",
  fan = "fan",
  humidifier = "humidifier",
  input_boolean = "input_boolean",
  input_button = "input_button",
  light = "light",
  lock = "lock",
  media_player = "media_player",
  scene = "scene",
  script = "script",
  sensor = "sensor",
  switch = "switch",
}
