export enum HomeAssistantDomain {
  light = "light",
  switch = "switch",
  lock = "lock",
  fan = "fan",
  binary_sensor = "binary_sensor",
  sensor = "sensor",
  cover = "cover",
  climate = "climate",
  input_boolean = "input_boolean",
  script = "script",
  automation = "automation",
  scene = "scene",
  media_player = "media_player",
  humidifier = "humidifier",
}
